=== urbanoliver/HEPMIU_XMLGyak/XMLTaskHEPMIU/1.feladat/XMLSchemaHepmiu.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema">

<!-- SAJÁT TÍPUS MEGHATÁROZÁSA-->

<xs:simpleType name="fejlettségTipus">
		<xs:restriction base="xs:string">
			<xs:enumeration value="erős"/>
            <xs:enumeration value="közepes"/>
			<xs:enumeration value="gyenge"/>
			
		</xs:restriction>
</xs:simpleType>


<!-- KOMLEX TÍPUSOK MEGHATÁROZÁSA-->
  <xs:element name="Hadsereg_HEPMIU">
    <xs:complexType>
      <xs:sequence>

<!-- HADSEREG EGYED SÉMÁJA-->
        <xs:element name="Hadsereg">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="létszám" type="xs:int" />
              <xs:element name="országNév" type="xs:string" />
              <xs:element name="pozíció" type="xs:string" />
              <xs:element name="fejlettség">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ütőképesség" type="xs:fejlettségTipus" />
                    <xs:element name="támadás" type="xs:fejlettségTipus" />
                    <xs:element name="védekezés" type="xs:fejlettségTipus" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="hadseregID" type="xs:int" use="required" />
          </xs:complexType>
        </xs:element>



<!--FŐPARANCSNOK EGYED SÉMÁJA-->
        <xs:element name="Főparancsnok">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="név" type="xs:string" />
              <xs:element name="rang" type="xs:string" />
              <xs:element name="életkor" type="xs:int" />
              <xs:element name="szolgIdő" type="unsignedByte" />
            </xs:sequence>
            <xs:attribute name="F_sorszám" type="xs:int" use="required" />
            <xs:attribute name="irányítja" type="xs:int" use="required" />
          </xs:complexType>
        </xs:element>



<!--TISZTEK EGYED SÉMÁJA-->
        <xs:element maxOccurs="unbounded" name="Tisztek">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="név" type="xs:string" />
              <xs:element name="rang" type="xs:string" />
              <xs:element name="életkor" type="xs:int" />
              <xs:element name="szolgIdő" type="unsignedByte" />
            </xs:sequence>
            <xs:attribute name="T_sorszám" type="xs:int" use="required" />
            <xs:attribute name="F_parancsnok" type="xs:int" use="required" />
          </xs:complexType>
        </xs:element>



<!--KATONÁK EGYED SÉMÁJA-->
        <xs:element maxOccurs="unbounded" name="Katonák">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="név" type="xs:string" />
              <xs:element name="rang" type="xs:string" />
              <xs:element name="életkor" type="xs:int" />
              <xs:element name="szolgIdő" type="unsignedByte" />
            </xs:sequence>
            <xs:attribute name="K_sorszám" type="xs:int" use="required" />
            <xs:attribute name="T_parancsnok" type="xs:int" use="required" />
            <xs:attribute name="szolgHelye" type="xs:int" use="required" />
          </xs:complexType>
        </xs:element>



<!--SZFÖLDI ERŐK EGYED SÉMÁJA-->
        <xs:element name="Szárazföldi_erők">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="létszám" type="xs:int" />
              <xs:element name="SzföldiJárművekSzáma" type="xs:int" />
            </xs:sequence>
            <xs:attribute name="SzE_ID" type="xs:int" use="required" />
          </xs:complexType>
        </xs:element>



<!--TENGERÉSZET EGYED SÉMÁJA-->
        <xs:element name="Tengerészet">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="létszám" type="xs:int" />
              <xs:element name="HajókSzáma" type="xs:int" />
            </xs:sequence>
            <xs:attribute name="Teng_ID" type="xs:int" use="required" />
          </xs:complexType>
        </xs:element>



<!--LÉGIERŐ EGYED SÉMÁJA-->
        <xs:element name="Légierő">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="létszám" type="xs:int" />
              <xs:element name="RepülőkSzáma" type="xs:int" />
            </xs:sequence>
            <xs:attribute name="Leg_ID" type="xs:int" use="required" />
          </xs:complexType>
        </xs:element>



      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== urbanoliver/HEPMIU_XMLGyak/XMLTaskHEPMIU/1.feladat/XMLHepmiu.xml
<?xml version="1.0" encoding="UTF-8"?>

<Hadsereg_HEPMIU xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="XMLSchemaHEPMIU.xsd">

<!--HADSEREG PÉLDÁNYOSÍTÁSA-->

<Hadsereg hadseregID="1">
    <létszám>9000</létszám>
    <országNév>Hungary</országNév>
    <pozíció>Dél-Alföld</pozíció>
    <fejlettség>
        <ütőképesség>közepes</ütőképesség>
        <támadás>erős</támadás>
        <védekezés>gyenge</védekezés>
    </fejlettség>

</Hadsereg>

<!--FŐPARANCSNOK PÉLDÁNYOSÍTÁSA-->
<Főparancsnok F_sorszám="4545" irányítja="1">
    <név>Nagy József</név>
    <rang>vezérezredes</rang>
    <életkor>56</életkor>
    <szolgIdő>30</szolgIdő>
</Főparancsnok>


<!--TISZTEK PÉLDÁNYOSÍTÁSA-->
<Tisztek T_sorszám="2323" F_parancsnok="4545">
    <név>Király Zoltán</név>
    <rang>százados</rang>
    <életkor>42</életkor>
    <szolgIdő>22</szolgIdő>
</Tisztek>

<Tisztek T_sorszám="2336" F_parancsnok="4545">
    <név>Nagy Zsolt</név>
    <rang>ezredes</rang>
    <életkor>48</életkor>
    <szolgIdő>28</szolgIdő>
</Tisztek>

<Tisztek T_sorszám="9836" F_parancsnok="4545">
    <név>Szabó Gyula</név>
    <rang>őrnagy</rang>
    <életkor>50</életkor>
    <szolgIdő>30</szolgIdő>
</Tisztek>


<!--KATONÁK PÉLDÁNYOSÍTÁSA-->

<Katonák K_sorszám="7874" T_parancsnok="9836" szolgHelye="56">
    <név>Szabó Kristóf</név>
    <rang>tizedes</rang>
    <életkor>20</életkor>
    <szolgIdő>1</szolgIdő>

</Katonák>

<Katonák K_sorszám="4921" T_parancsnok="9836" szolgHelye="56">
    <név>Tóth Bendegúz</név>
    <rang>hadnagy</rang>
    <életkor>28</életkor>
    <szolgIdő>10</szolgIdő>

</Katonák>

<Katonák K_sorszám="7123" T_parancsnok="9836" szolgHelye="56">
    <név>Nagy Márton</név>
    <rang>tizedes</rang>
    <életkor>23</életkor>
    <szolgIdő>3</szolgIdő>

</Katonák>


<!--FEGYVERNEMEK  PÉLDÁNYOSÍTÁSA-->
<Szárazföldi_erők SzE_ID="56">
    <létszám>5000</létszám>
    <SzföldiJárművekSzáma>250</SzföldiJárművekSzáma>

</Szárazföldi_erők>

<Tengerészet Teng_ID="23">
    <létszám>2000</létszám>
    <HajókSzáma>5</HajókSzáma>
</Tengerészet>

<Légierő Leg_ID="18">
    <létszám>2000</létszám>
    <RepülőkSzáma>120</RepülőkSzáma>
</Légierő>

</Hadsereg_HEPMIU>

=== urbanoliver/HEPMIU_XMLGyak/XMLTaskHEPMIU/2.feladat/DOMParseHepmiu/XMLHepmiu.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Hadsereg_HEPMIU xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="XMLSchemaHEPMIU.xsd">

<!--HADSEREG PÉLDÁNYOSÍTÁSA-->

<Hadsereg hadseregID="1">
    <létszám>9000</létszám>
    <országNév>Hungary</országNév>

    <pozíció>Dél-Alföld</pozíció>
    <pozíció>Tiszakoz</pozíció>
    <pozíció>Dunantul</pozíció>

    <fejlettség>
        <ütőképesség>közepes</ütőképesség>
        <támadás>erős</támadás>
        <védekezés>gyenge</védekezés>
    </fejlettség>

</Hadsereg>

<Hadsereg hadseregID="2">
    <létszám>6000</létszám>
    <országNév>Hungary</országNév>

    <pozíció>Dél-Alföld</pozíció>
    <pozíció>Duanatuli-kozephegyseg</pozíció>
    <pozíció>Vajdasag</pozíció>

    <fejlettség>
        <ütőképesség>gyenge</ütőképesség>
        <támadás>erős</támadás>
        <védekezés>gyenge</védekezés>
    </fejlettség>

</Hadsereg>

<Hadsereg hadseregID="3">
    <létszám>20000</létszám>
    <országNév>Hungary</országNév>

    <pozíció>Dél-Alföld</pozíció>
    <pozíció>Tiszakoz</pozíció>
    <pozíció>Eszaki-kozephegyseg</pozíció>

    <fejlettség>
        <ütőképesség>közepes</ütőképesség>
        <támadás>erős</támadás>
        <védekezés>közepes</védekezés>
    </fejlettség>

</Hadsereg>

<!--FŐPARANCSNOK PÉLDÁNYOSÍTÁSA-->
<Főparancsnok F_sorszám="4545" irányítja="1">
    <név>Nagy József</név>
    <rang>vezérezredes</rang>
    <életkor>56</életkor>
    <szolgIdő>30</szolgIdő>
</Főparancsnok>

<Főparancsnok F_sorszám="2245" irányítja="2">
    <név>Hári János</név>
    <rang>tábornagy</rang>
    <életkor>52</életkor>
    <szolgIdő>32</szolgIdő>
</Főparancsnok>

<Főparancsnok F_sorszám="1717" irányítja="3">
    <név>Kovács Zétény</név>
    <rang>tábornok</rang>
    <életkor>58</életkor>
    <szolgIdő>36</szolgIdő>
</Főparancsnok>


<!--TISZTEK PÉLDÁNYOSÍTÁSA-->
<Tisztek F_parancsnok="4545" T_sorszám="2323">
    <név>Király Zoltán</név>
    <rang>százados</rang>
    <életkor>42</életkor>
    <szolgIdő>22</szolgIdő>
</Tisztek>

<Tisztek F_parancsnok="4545" T_sorszám="2336">
    <név>Nagy Zsolt</név>
    <rang>ezredes</rang>
    <életkor>48</életkor>
    <szolgIdő>28</szolgIdő>
</Tisztek>

<Tisztek F_parancsnok="4545" T_sorszám="9836">
    <név>Szabó Gyula</név>
    <rang>őrnagy</rang>
    <életkor>50</életkor>
    <szolgIdő>30</szolgIdő>
</Tisztek>


<!--KATONÁK PÉLDÁNYOSÍTÁSA-->

<Katonák K_sorszám="7874" T_parancsnok="9836" szolgHelye="56">
    <név>Szabó Kristóf</név>
    <rang>tizedes</rang>
    <életkor>20</életkor>
    <szolgIdő>1</szolgIdő>

</Katonák>

<Katonák K_sorszám="4921" T_parancsnok="9836" szolgHelye="56">
    <név>Tóth Bendegúz</név>
    <rang>hadnagy</rang>
    <életkor>28</életkor>
    <szolgIdő>10</szolgIdő>

</Katonák>

<Katonák K_sorszám="7123" T_parancsnok="9836" szolgHelye="56">
    <név>Kovács István</név>
    <rang>tizedes</rang>
    <életkor>23</életkor>
    <szolgIdő>3</szolgIdő>

</Katonák>


<!--FEGYVERNEMEK  PÉLDÁNYOSÍTÁSA-->



<!--SZARAZFOLDI EROK  PÉLDÁNYOSÍTÁSA-->
<Szárazföldi_erők SzE_ID="56">
    <létszám>5000</létszám>
    <SzföldiJárművekSzáma>250</SzföldiJárművekSzáma>

</Szárazföldi_erők>

<Szárazföldi_erők SzE_ID="12">
    <létszám>2500</létszám>
    <SzföldiJárművekSzáma>125</SzföldiJárművekSzáma>

</Szárazföldi_erők>

<Szárazföldi_erők SzE_ID="36">
    <létszám>6800</létszám>
    <SzföldiJárművekSzáma>550</SzföldiJárművekSzáma>

</Szárazföldi_erők>




<!--TENGERESZET  PÉLDÁNYOSÍTÁSA-->
<Tengerészet Teng_ID="26">
    <létszám>2000</létszám>
    <HajókSzáma>6</HajókSzáma>
</Tengerészet>

<Tengerészet Teng_ID="48">
    <létszám>2500</létszám>
    <HajókSzáma>5</HajókSzáma>
</Tengerészet>

<Tengerészet Teng_ID="23">
    <létszám>3600</létszám>
    <HajókSzáma>12</HajókSzáma>
</Tengerészet>




<!--LEGIERO  PÉLDÁNYOSÍTÁSA-->
<Légierő Leg_ID="13">
    <létszám>1500</létszám>
    <RepülőkSzáma>90</RepülőkSzáma>
</Légierő>

<Légierő Leg_ID="21">
    <létszám>3400</létszám>
    <RepülőkSzáma>120</RepülőkSzáma>
</Légierő>

<Légierő Leg_ID="18">
    <létszám>4000</létszám>
    <RepülőkSzáma>150</RepülőkSzáma>
</Légierő>

</Hadsereg_HEPMIU>
